include: package:flutter_lints/flutter.yaml

analyzer:
   errors:
     invalid_annotation_target: ignore
   plugins:
     - dart_code_metrics
   exclude:
     - "**/*.mocks.dart"
     - "**/**.g.dart"
     - "**/**.freezed.dart"
     - lib/l10n/**

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true

dart_code_metrics:
   anti-patterns:
     - long-method
     - long-parameter-list
   metrics:
     cyclomatic-complexity: 20
     maximum-nesting-level: 5
     number-of-parameters: 4
     source-lines-of-code: 50
   metrics-exclude:
     - test/**
   rules:
     - newline-before-return
     - no-boolean-literal-compare
     - no-empty-block
     - prefer-trailing-comma
     - prefer-conditional-expressions
     - no-equal-then-else
   rules-exclude:
     - test/**
     - lib/**.freezed.dart
     - lib/**.g.dart
     - no-equal-arguments:
         exclude:
           - lib/**.freezed.dart
           - lib/**.g.dart
           - test/**