include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.mocks.dart"
    - "**/**.g.dart"
    - "**/**.freezed.dart"
    - lib/l10n/**

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
    always_declare_return_types: true
    always_use_package_imports: true