name: flutter_shop
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  bloc_concurrency: ^0.2.0
  collection: ^1.16.0
  cupertino_icons: ^1.0.5
  firebase_core: ^1.19.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  formz: ^0.4.1
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  http: ^0.13.4
  http_interceptor: ^1.0.2
  intl: ^0.17.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.1.11
  dart_code_metrics: ^4.15.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  mockito: ^5.2.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/product_placeholder.png

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
