// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFezEBqMHyNiBmR6_KdhH_57A-RlQoWUE',
    appId: '1:450102488463:web:51bb03106c8d2c755eaffa',
    messagingSenderId: '450102488463',
    projectId: 'fir-flutter-shop-cd4c3',
    authDomain: 'fir-flutter-shop-cd4c3.firebaseapp.com',
    storageBucket: 'fir-flutter-shop-cd4c3.appspot.com',
    measurementId: 'G-9E30ZXM9WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYZHqDYBz5h8C-97UmYxunH6WY87qjMUc',
    appId: '1:450102488463:android:2c871be11970f9e75eaffa',
    messagingSenderId: '450102488463',
    projectId: 'fir-flutter-shop-cd4c3',
    storageBucket: 'fir-flutter-shop-cd4c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaS5PfkVZ-GaV2zokQlgT2nzR5uQpHqx8',
    appId: '1:450102488463:ios:64937ff1eed24ffb5eaffa',
    messagingSenderId: '450102488463',
    projectId: 'fir-flutter-shop-cd4c3',
    storageBucket: 'fir-flutter-shop-cd4c3.appspot.com',
    iosClientId:
        '450102488463-ld84lcp0h97i6un543ags7rrhljg7gtl.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp',
  );
}
