# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    environment: app_config

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2.4.0
        with:
          flutter-version: '3.0.4'

      - run: echo $SECRETS_FILE_CONTENT | base64 -d > lib/secrets.dart
        env:
          SECRETS_FILE_CONTENT: ${{ secrets.SECRETS_FILE_CONTENT }}

      - run: flutter pub get
      - run: dart format lib lib/ --output=none --set-exit-if-changed
      - run: flutter analyze
      - run: flutter test


  build_ios:
    name: Build flutter (IOS)
    needs: [flutter_test]
    runs-on: macos-latest
    environment: app_config

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.4.0
        with:
          flutter-version: '3.0.4'
          architecture: x64
      - run: echo $SECRETS_FILE_CONTENT | base64 -d > lib/secrets.dart
        env:
          SECRETS_FILE_CONTENT: ${{ secrets.SECRETS_FILE_CONTENT }}

      - run: flutter clean
      - run: flutter pub get
      - run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - run: flutter gen-l10n
      - run: flutter build ios --release --no-codesign --flavor prod --target lib/main_prod.dart


  build_android:
    name: Build flutter (android)
    needs: [ flutter_test ]
    runs-on: ubuntu-latest
    environment: app_config

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2.4.0
        with:
          flutter-version: '3.0.4'

      - run: echo $SECRETS_FILE_CONTENT | base64 -d > lib/secrets.dart
        env:
          SECRETS_FILE_CONTENT: ${{ secrets.SECRETS_FILE_CONTENT }}

      - run: flutter pub get
      - run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - run: flutter gen-l10n
      - run: flutter build apk --release --flavor prod --target lib/main_prod.dart
      - run: flutter build appbundle --release --flavor prod --target lib/main_prod.dart

      
        
        
